### ISSUE TITLE
Changing something in detail view does not update text in main view

### ISSUE THREAD

**Issue by sg-s** [sg-s/whats-cooking#5]

**Comment by Yonodactyl** [comment]
Why don’t you try and output any errors in the update method inside DetailView? It might be resulting in the error thrown not being handled?

**Comment by sg-s** [comment]
thanks for getting involved! 

the problem is there are no errors. The app compiles and runs, but the list view isn't getting updated. 




![Screen Shot 2020-04-12 at 10 08 36 AM](https://user-images.githubusercontent.com/6005346/79070734-b2d56900-7ca5-11ea-9cef-668458252f26.png)

**Comment by Yonodactyl** [comment]
I’d love to work on this with you if you’ll allow me??

**Comment by sg-s** [comment]
Sure thing! I think I've figured out why it doens't work -- it works when the contents of RowView are inlined in the main ContentView. When I pass recipe into RowView, it's passed by value, not reference, which is why it doesn't update.

I think

**Comment by sg-s** [comment]
@Yonodactyl I got around the problem by in-lining RowView
